language: node_js
node_js: node
cache:
 directories:
   - node_modules
script:
 - npm test
env:
 - CI=true

before_deploy:
 - npm install netlify-cli -g
 - process.env.REACT_APP_API_BASE_URL="https://artseen-nyc-api.herokuapp.com/api" npm run build

deploy:
 provider: script
 script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
 skip_cleanup: true
 on:
   branch: master